# Generated by Django 2.2 on 2020-01-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_pet_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='pet_services',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
