# Generated by Django 2.2 on 2020-01-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200114_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_services',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pet_services',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
