# Generated by Django 2.2 on 2020-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200114_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_services',
            name='status',
            field=models.NullBooleanField(default=0, max_length=5, verbose_name='Payment Processed status'),
        ),
    ]
