# Generated by Django 2.2 on 2020-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_pet_services_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_services',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
