# Generated by Django 3.0.2 on 2020-03-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_pet_services_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet_services',
            options={'verbose_name_plural': 'Pets'},
        ),
    ]
