# Generated by Django 3.0.2 on 2020-03-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
