# Generated by Django 3.0.2 on 2020-03-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_services',
            name='genre',
            field=models.CharField(choices=[('Pet', 'Pet'), ('Service', 'Service')], default='Pet', max_length=255),
        ),
    ]
